name: DENTAL
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.9,<3.12
  
  # Core data science libraries
  - pandas>=2.0.0,<3.0.0
  - numpy>=1.24.0,<2.0.0
  - scipy>=1.10.0,<2.0.0
  
  # Visualization
  - matplotlib>=3.7.0,<4.0.0
  - seaborn>=0.12.0,<1.0.0
  - plotly>=5.14.0,<6.0.0
  
  # Machine Learning
  - scikit-learn>=1.3.0,<2.0.0
  - xgboost>=1.7.0,<2.0.0
  - imbalanced-learn>=0.11.0,<1.0.0
  
  # Statistical Analysis
  - statsmodels>=0.14.0,<1.0.0
  
  # Data I/O
  - pyarrow>=12.0.0,<14.0.0
  
  # Model Persistence
  - joblib>=1.3.0,<2.0.0
  
  # Jupyter Environment
  - jupyter>=1.0.0,<2.0.0
  - notebook>=6.5.0,<8.0.0
  
  # Development tools
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - catboost>=1.2.0,<2.0.0
    - shap>=0.42.0,<1.0.0
    - lime>=0.2.0,<1.0.0
    - optuna>=3.2.0,<4.0.0
    - sas7bdat>=2.2.0,<3.0.0
    - pyreadstat>=1.2.0,<2.0.0
    - tensorflow>=2.13.0,<3.0.0
    - torch>=2.0.0,<3.0.0
